### ISSUE TITLE
Ajout de quelques paragraphes

### ISSUE THREAD

**Issue by t00sh** [t00sh/mastercsi-per#15]
Comme précisé dans #13 j'ai ajouté deux nouveaux paragraphes qu'il faut rédiger.

Il reste donc à rédiger les sections suivantes : 

- [x] Le persistent mode
- [x] Les autres versions de AFL (pour ARM par exemple)
- [x] L'introduction
- [x] La conclusion

**Comment by Gr0minet** [comment]
Pas sûr qu'une conclusion soit très pertinente vu qu'on a rien produit et qu'on ne fait qu'expliquer des choses. À la limite on peut parler des bugs trouvés en fuzzant r2 pour bien insister sur l'efficacité de la technique.
J'écris une petite introduction atm.

**Comment by t00sh** [comment]
En conclusion, je pensais qu'on pourrait ouvrir sur le Fuzzing project, le OSS-fuzz de google et sur libfuzzer par exemple.

**Comment by Gr0minet** [comment]
Ok ouais je vois l'idée, c'est pas vraiment une conclusion du coup mais plutôt une partie sur les alternatives à AFL. Ce qui a du sens.

**Comment by Gr0minet** [comment]
Je fais une conclusion
