### ISSUE TITLE
Restyliser `afl-gcc` et `afl-fuzz` dans le chapitre 1

### ISSUE THREAD

**Issue by Pamplemousse** [t00sh/mastercsi-per#7]
Petite inconsistence de style : dans le chapitre 2, les "commandes" d'AFL (`afl-gcc`, `afl-fuzz`) sont écrites dans des macros `lstinline{}`, alors que ce n'est pas le cas dans le chapitre 1.

**Comment by Gr0minet** [comment]
Mince du coup on aurait pas du merge ma branche :thinking: On fait les changements sur quelle branche alors ?

**Comment by Pamplemousse** [comment]
Si tu parles de #4 , c'est bien `brendan-branch` qui a été mergé.
